// Seed catalog. Photos are hotlinked from Unsplash (free to use under the
// Unsplash License). Only the base url is stored, the client adds the size.
// Every photo was checked by eye and shows no third party logo or brand mark,
// keep it that way when adding products.

export const photo = (id: string) => `https://images.unsplash.com/photo-${id}`

const COLORS = {
  blue: { name: 'Sky Blue', hex: '#23A6F0' },
  green: { name: 'Forest Green', hex: '#23856D' },
  orange: { name: 'Sunset Orange', hex: '#E77C40' },
  navy: { name: 'Midnight Navy', hex: '#252B42' },
  white: { name: 'Off White', hex: '#F5F5F5' },
  black: { name: 'Jet Black', hex: '#1B1B1B' },
  red: { name: 'Crimson Red', hex: '#E74040' },
  grey: { name: 'Stone Grey', hex: '#9E9E9E' },
  tan: { name: 'Camel Tan', hex: '#C19A6B' },
  pink: { name: 'Blush Pink', hex: '#F4B6C2' },
  yellow: { name: 'Sun Yellow', hex: '#F7C948' },
  burgundy: { name: 'Burgundy', hex: '#7B1E3A' },
} as const

type ColorKey = keyof typeof COLORS

const SIZES = {
  clothing: ['XS', 'S', 'M', 'L', 'XL'],
  kids: ['2Y', '4Y', '6Y', '8Y', '10Y'],
  shoes: ['38', '39', '40', '41', '42', '43', '44'],
  none: [] as string[],
}

export interface SeedCategory {
  slug: string
  name: string
  description: string
  image: string
  order: number
}

export const categories: SeedCategory[] = [
  {
    slug: 'men',
    name: 'Men',
    description: 'Everyday essentials, sharp tailoring and outerwear built to last.',
    image: photo('1516826957135-700dedea698c'),
    order: 1,
  },
  {
    slug: 'women',
    name: 'Women',
    description: 'Dresses, knitwear and coats for every part of the week.',
    image: photo('1469334031218-e382a71b716b'),
    order: 2,
  },
  {
    slug: 'accessories',
    name: 'Accessories',
    description: 'Watches, bags and finishing touches that pull a look together.',
    image: photo('1594223274512-ad4803739b7c'),
    order: 3,
  },
  {
    slug: 'kids',
    name: 'Kids',
    description: 'Soft, tough and easy to wash clothes for small adventurers.',
    image: photo('1503944583220-79d8926ad5e2'),
    order: 4,
  },
  {
    slug: 'shoes',
    name: 'Shoes',
    description: 'Boots, loafers, heels and sandals for the road ahead.',
    image: photo('1638609348722-aa2a3a67db26'),
    order: 5,
  },
]

type SizeKey = keyof typeof SIZES

interface ProductInput {
  name: string
  department: string
  summary: string
  price: number
  was?: number
  images: string[]
  colors: ColorKey[]
  stock: number
  sales: number
  tags: string[]
  featured?: boolean
  bestseller?: boolean
  sizes?: SizeKey
}

export interface SeedProduct {
  name: string
  slug: string
  department: string
  category: string
  summary: string
  description: string
  highlights: string[]
  price: number
  compareAtPrice: number | null
  images: string[]
  colors: Array<{ name: string; hex: string }>
  sizes: string[]
  stock: number
  salesCount: number
  tags: string[]
  featured: boolean
  bestseller: boolean
}

const CATEGORY_COPY: Record<string, { sizes: SizeKey; description: string; highlights: string[] }> = {
  men: {
    sizes: 'clothing',
    description:
      'Cut for a relaxed, modern fit and finished with reinforced seams, this piece is made to be worn often and washed without worry. The fabric is pre-washed, so it keeps its shape and colour from the first wear.',
    highlights: [
      'Pre-washed fabric that keeps its shape',
      'Reinforced seams at stress points',
      'Machine wash cold, tumble dry low',
      'Free returns within 30 days',
    ],
  },
  women: {
    sizes: 'clothing',
    description:
      'Designed in small batches with a flattering drape and considered details. The fabric is soft against the skin, breathable through the day and easy to care for at home.',
    highlights: [
      'Soft, breathable fabric with natural drape',
      'Considered details and clean finishing',
      'Machine wash cold on a gentle cycle',
      'Free returns within 30 days',
    ],
  },
  kids: {
    sizes: 'kids',
    description:
      'Made for playgrounds, puddles and everything in between. Gentle on sensitive skin, tough at the knees and elbows, and happy to go through the wash again and again.',
    highlights: [
      'Gentle on sensitive skin',
      'Easy on, easy off fastenings',
      'Holds up to frequent washing',
      'Free returns within 30 days',
    ],
  },
  accessories: {
    sizes: 'none',
    description:
      'A finishing touch built from quality materials and checked by hand before it ships. It arrives in a recycled gift box and is covered by a two year warranty.',
    highlights: [
      'Quality materials, checked by hand',
      'Arrives in a recycled gift box',
      'Two year warranty included',
      'Free returns within 30 days',
    ],
  },
  shoes: {
    sizes: 'shoes',
    description:
      'A cushioned footbed and a durable outsole keep you comfortable from the first step to the last. True to size, with a padded collar and a grippy tread for wet pavements.',
    highlights: [
      'Cushioned, removable footbed',
      'Durable outsole with wet weather grip',
      'Fits true to size',
      'Free returns within 30 days',
    ],
  },
}

function slugOf(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function build(category: string, items: ProductInput[]): SeedProduct[] {
  const copy = CATEGORY_COPY[category]
  return items.map((item) => ({
    name: item.name,
    slug: slugOf(item.name),
    department: item.department,
    category,
    summary: item.summary,
    description: `${item.summary} ${copy.description}`,
    highlights: copy.highlights,
    price: item.price,
    compareAtPrice: item.was ?? null,
    images: item.images.map(photo),
    colors: item.colors.map((key) => COLORS[key]),
    sizes: SIZES[item.sizes ?? copy.sizes],
    stock: item.stock,
    salesCount: item.sales,
    tags: item.tags,
    featured: item.featured ?? false,
    bestseller: item.bestseller ?? false,
  }))
}

const men = build('men', [
  {
    name: 'Essential White Tee',
    department: 'Everyday Basics',
    summary: 'A heavyweight cotton tee with a clean crew neck, the one you reach for first.',
    price: 1948,
    was: 2600,
    images: ['1521572163474-6864f9cf17ab', '1562157873-818bc0726f68'],
    colors: ['white', 'black', 'navy', 'grey'],
    stock: 120,
    sales: 412,
    tags: ['tee', 'cotton', 'basics'],
    bestseller: true,
  },
  {
    name: 'Breton Stripe Tee',
    department: 'Everyday Basics',
    summary: 'A classic striped tee in midweight cotton jersey with a relaxed crew neck.',
    price: 2448,
    was: 3200,
    images: ['1591224615614-e300d72e37c5'],
    colors: ['navy', 'black', 'white'],
    stock: 64,
    sales: 187,
    tags: ['tee', 'stripes', 'cotton'],
    featured: true,
  },
  {
    name: 'Moto Leather Jacket',
    department: 'Outerwear',
    summary: 'A classic asymmetric biker jacket in full grain leather with polished hardware.',
    price: 18900,
    was: 24900,
    images: ['1551028719-00167b16eac5', '1520975954732-35dd22299614'],
    colors: ['black', 'burgundy'],
    stock: 18,
    sales: 96,
    tags: ['jacket', 'leather', 'outerwear'],
    featured: true,
    bestseller: true,
  },
  {
    name: 'Selvedge Denim Jeans',
    department: 'Denim Lab',
    summary: 'Straight leg jeans in rigid selvedge denim that soften and fade with wear.',
    price: 7900,
    images: ['1714143164072-7646ef5cb24d', '1604176354204-9268737828e4'],
    colors: ['navy', 'black'],
    stock: 75,
    sales: 264,
    tags: ['jeans', 'denim'],
    bestseller: true,
  },
  {
    name: 'Washed Black Jeans',
    department: 'Denim Lab',
    summary: 'Slim tapered jeans in washed black stretch denim with a turn up hem.',
    price: 6900,
    was: 8400,
    images: ['1718252540511-e958742e4165'],
    colors: ['black', 'grey'],
    stock: 58,
    sales: 142,
    tags: ['jeans', 'denim'],
  },
  {
    name: 'Coral Bomber Jacket',
    department: 'Outerwear',
    summary: 'A lightweight bomber with ribbed trims and a smooth satin lining.',
    price: 8900,
    was: 11900,
    images: ['1591047139829-d91aecb6caea'],
    colors: ['orange', 'navy', 'green'],
    stock: 42,
    sales: 133,
    tags: ['jacket', 'bomber', 'outerwear'],
    featured: true,
  },
  {
    name: 'Midnight Crew Tee',
    department: 'Everyday Basics',
    summary: 'A jet black tee in soft combed cotton, cut slightly longer in the body.',
    price: 2248,
    images: ['1571455786673-9d9d6c194f90', '1610502778270-c5c6f4c7d575'],
    colors: ['black', 'white'],
    stock: 88,
    sales: 205,
    tags: ['tee', 'cotton', 'basics'],
  },
  {
    name: 'Cloud Grey Hoodie',
    department: 'Loungewear',
    summary: 'A brushed fleece hoodie with a double lined hood and a roomy kangaroo pocket.',
    price: 5400,
    was: 6800,
    images: ['1556821840-3a63f95609a7'],
    colors: ['grey', 'black', 'navy'],
    stock: 96,
    sales: 348,
    tags: ['hoodie', 'fleece', 'loungewear'],
    bestseller: true,
  },
  {
    name: 'Relaxed Knit Sweater',
    department: 'Knitwear',
    summary: 'A midweight cotton knit with dropped shoulders for an easy, relaxed shape.',
    price: 6200,
    images: ['1620799140408-edc6dcb6d633'],
    colors: ['white', 'grey', 'tan'],
    stock: 51,
    sales: 119,
    tags: ['sweater', 'knitwear'],
  },
  {
    name: 'Chambray Denim Shirt',
    department: 'Denim Lab',
    summary: 'A washed chambray shirt with pearl snaps and twin chest pockets.',
    price: 5800,
    was: 7200,
    images: ['1596755094514-f87e34085b2c'],
    colors: ['blue', 'navy'],
    stock: 60,
    sales: 171,
    tags: ['shirt', 'denim'],
    featured: true,
  },
  {
    name: 'Oxford Shirt Trio',
    department: 'Tailoring',
    summary: 'Three button down Oxford shirts in the colours you will wear every week.',
    price: 9800,
    was: 12900,
    images: ['1602810318383-e386cc2a3ccf'],
    colors: ['white', 'blue', 'pink'],
    stock: 34,
    sales: 88,
    tags: ['shirt', 'oxford', 'set'],
  },
  {
    name: 'Tailored Navy Suit',
    department: 'Tailoring',
    summary: 'A two piece suit in a wool blend with a half canvas construction and a slim lapel.',
    price: 32900,
    was: 39900,
    images: ['1594938298603-c8148c4dae35', '1617137968427-85924c800a22', '1507679799987-c73779587ccf'],
    colors: ['navy', 'black', 'grey'],
    stock: 22,
    sales: 74,
    tags: ['suit', 'tailoring', 'formal'],
    featured: true,
  },
  {
    name: 'Everyday Tee Four Pack',
    department: 'Everyday Basics',
    summary: 'Four of our softest tees in one pack, so laundry day can wait.',
    price: 5900,
    was: 7800,
    images: ['1562157873-818bc0726f68'],
    colors: ['red', 'black', 'white', 'navy'],
    stock: 140,
    sales: 301,
    tags: ['tee', 'basics', 'set'],
  },
])

const women = build('women', [
  {
    name: 'Sunshine Two Piece Set',
    department: 'Summer Edit',
    summary: 'A matching jacket and trouser set in a bright, sun washed yellow.',
    price: 11800,
    was: 14900,
    images: ['1515886657613-9f3515b0c78f'],
    colors: ['yellow', 'white', 'blue'],
    stock: 38,
    sales: 226,
    tags: ['set', 'summer', 'co-ord'],
    featured: true,
    bestseller: true,
  },
  {
    name: 'Garden Floral Dress',
    department: 'Summer Edit',
    summary: 'A floaty midi dress with a hand drawn floral print and a tie waist.',
    price: 7400,
    was: 9600,
    images: ['1496747611176-843222e1e57c'],
    colors: ['white', 'pink', 'blue'],
    stock: 57,
    sales: 298,
    tags: ['dress', 'floral', 'summer'],
    bestseller: true,
  },
  {
    name: 'Scarlet Wrap Dress',
    department: 'Occasion Wear',
    summary: 'A wrap dress in fluid crepe that moves beautifully and flatters every shape.',
    price: 9800,
    images: ['1572804013309-59a88b7e92f1', '1595777457583-95e059d581b8'],
    colors: ['red', 'black', 'green'],
    stock: 44,
    sales: 243,
    tags: ['dress', 'occasion'],
    featured: true,
    bestseller: true,
  },
  {
    name: 'Seaside Linen Dress',
    department: 'Summer Edit',
    summary: 'A breezy linen maxi dress made for warm evenings and sandy boardwalks.',
    price: 8600,
    was: 10800,
    images: ['1539008835657-9e8e9680c956', '1475180098004-ca77a66827be'],
    colors: ['blue', 'white'],
    stock: 49,
    sales: 157,
    tags: ['dress', 'linen', 'summer'],
  },
  {
    name: 'Heritage Plaid Coat',
    department: 'Outerwear',
    summary: 'A double breasted wool blend coat in a deep heritage check.',
    price: 16800,
    was: 21000,
    images: ['1485968579580-b6d095142e6e'],
    colors: ['navy', 'green', 'burgundy'],
    stock: 26,
    sales: 102,
    tags: ['coat', 'wool', 'outerwear'],
    featured: true,
  },
  {
    name: 'Cream Knit Top',
    department: 'Knitwear',
    summary: 'An open knit top in soft cotton yarn, light enough to layer all year.',
    price: 4800,
    images: ['1434389677669-e08b4cac3105'],
    colors: ['white', 'tan', 'pink'],
    stock: 71,
    sales: 184,
    tags: ['top', 'knitwear'],
  },
  {
    name: 'Blush Wool Coat',
    department: 'Outerwear',
    summary: 'A longline coat in brushed wool with a soft shoulder and deep pockets.',
    price: 18400,
    was: 22900,
    images: ['1485462537746-965f33f7f6a7'],
    colors: ['pink', 'tan', 'grey'],
    stock: 19,
    sales: 91,
    tags: ['coat', 'wool', 'outerwear'],
  },
  {
    name: 'Striped Shirt and Skirt Set',
    department: 'Workwear',
    summary: 'A crisp striped shirt paired with a pleated skirt for an easy office look.',
    price: 8900,
    images: ['1583496661160-fb5886a0aaaa'],
    colors: ['white', 'black', 'navy'],
    stock: 40,
    sales: 126,
    tags: ['set', 'shirt', 'skirt', 'workwear'],
  },
  {
    name: 'Denim Button Dress',
    department: 'Denim Lab',
    summary: 'A button through denim dress with a defined waist and a gentle flare.',
    price: 6900,
    was: 8400,
    images: ['1591369822096-ffd140ec948f'],
    colors: ['blue', 'navy'],
    stock: 63,
    sales: 211,
    tags: ['dress', 'denim'],
    bestseller: true,
  },
  {
    name: 'Breton Stripe Top',
    department: 'Everyday Basics',
    summary: 'A boat neck striped top in soft cotton, the easiest thing in your wardrobe.',
    price: 2400,
    images: ['1606313323084-1b62c6c541d8', '1622413472627-be5d5af1c577'],
    colors: ['navy', 'black', 'white'],
    stock: 82,
    sales: 176,
    tags: ['top', 'stripes', 'cotton'],
  },
  {
    name: 'Rose Ruffle Blouse',
    department: 'Occasion Wear',
    summary: 'A romantic blouse with tiered ruffles and delicate covered buttons.',
    price: 6400,
    was: 7900,
    images: ['1581044777550-4cfa60707c03'],
    colors: ['pink', 'white'],
    stock: 36,
    sales: 98,
    tags: ['blouse', 'occasion'],
    featured: true,
  },
  {
    name: 'Powder Blue Trench',
    department: 'Outerwear',
    summary: 'A water resistant trench in powder blue with a removable belt.',
    price: 14900,
    images: ['1539109136881-3be0616acf4b'],
    colors: ['blue', 'tan', 'navy'],
    stock: 28,
    sales: 84,
    tags: ['coat', 'trench', 'outerwear'],
  },
  {
    name: 'Slate Cotton Tee',
    department: 'Everyday Basics',
    summary: 'A slim fit tee in washed slate cotton with a slightly scooped neck.',
    price: 1848,
    was: 2400,
    images: ['1564584217132-2271feaeb3c5'],
    colors: ['grey', 'white', 'black', 'blue'],
    stock: 110,
    sales: 263,
    tags: ['tee', 'cotton', 'basics'],
  },
])

const kids = build('kids', [
  {
    name: 'Little Gentleman Set',
    department: 'Mini Occasion',
    summary: 'A smart shirt, shorts and bow tie set for parties and family photos.',
    price: 4600,
    was: 5800,
    images: ['1519238263530-99bdd11df2ea'],
    colors: ['blue', 'navy', 'white'],
    stock: 45,
    sales: 132,
    tags: ['set', 'occasion', 'boys'],
    featured: true,
  },
  {
    name: 'Cozy Bear Onesie',
    department: 'Baby Soft',
    summary: 'A fleece lined onesie with tiny bear ears on the hood.',
    price: 3800,
    images: ['1522771930-78848d9293e8'],
    colors: ['tan', 'grey', 'white'],
    stock: 58,
    sales: 219,
    tags: ['onesie', 'baby', 'fleece'],
    bestseller: true,
  },
  {
    name: 'Polka Dot Party Dress',
    department: 'Mini Occasion',
    summary: 'A twirl ready cotton dress covered in tiny polka dots.',
    price: 4200,
    was: 5400,
    images: ['1518831959646-742c3a14ebf7'],
    colors: ['white', 'pink', 'red'],
    stock: 39,
    sales: 148,
    tags: ['dress', 'occasion', 'girls'],
    featured: true,
  },
  {
    name: 'Cherry Red Kids Tee',
    department: 'Play Basics',
    summary: 'A bright, soft tee that survives paint, grass and second helpings.',
    price: 1400,
    was: 1800,
    images: ['1471286174890-9c112ffca5b4'],
    colors: ['red', 'blue', 'yellow', 'green'],
    stock: 150,
    sales: 326,
    tags: ['tee', 'basics'],
    bestseller: true,
  },
  {
    name: 'Sunny Day Raincoat',
    department: 'Outdoor Kids',
    summary: 'A fully waterproof raincoat in puddle proof yellow with taped seams.',
    price: 4900,
    images: ['1503919545889-aef636e10ad4'],
    colors: ['yellow', 'red', 'blue'],
    stock: 47,
    sales: 173,
    tags: ['raincoat', 'outerwear'],
    featured: true,
  },
  {
    name: 'Mini Plaid Shirt',
    department: 'Play Basics',
    summary: 'A brushed cotton plaid shirt, just like the grown up one.',
    price: 2600,
    was: 3200,
    images: ['1514090458221-65bb69cf63e6'],
    colors: ['blue', 'red', 'green'],
    stock: 66,
    sales: 94,
    tags: ['shirt', 'plaid'],
  },
  {
    name: 'Organic Cotton Kids Tee',
    department: 'Play Basics',
    summary: 'A plain tee in certified organic cotton, kind to skin and the planet.',
    price: 1200,
    images: ['1622290291468-a28f7a7dc6a8'],
    colors: ['white', 'grey', 'pink'],
    stock: 130,
    sales: 207,
    tags: ['tee', 'organic', 'basics'],
  },
])

const accessories = build('accessories', [
  {
    name: 'Minimalist White Watch',
    department: 'Timepieces',
    summary: 'A slim 40mm watch with a clean dial and a soft silicone strap.',
    price: 12900,
    was: 15900,
    images: ['1523275335684-37898b6baf30'],
    colors: ['white', 'black'],
    stock: 33,
    sales: 288,
    tags: ['watch', 'minimal'],
    featured: true,
    bestseller: true,
  },
  {
    name: 'Heritage Field Watch',
    department: 'Timepieces',
    summary: 'A hand finished field watch with a domed crystal and a leather strap.',
    price: 16900,
    images: ['1524592094714-0f0654e20314'],
    colors: ['tan', 'black'],
    stock: 27,
    sales: 112,
    tags: ['watch', 'leather'],
  },
  {
    name: 'Round Wire Sunglasses',
    department: 'Eyewear',
    summary: 'Lightweight round frames in brushed gold wire with green tinted lenses.',
    price: 5900,
    was: 7400,
    images: ['1511499767150-a48a237f0083'],
    colors: ['tan', 'black'],
    stock: 68,
    sales: 164,
    tags: ['sunglasses', 'eyewear'],
  },
  {
    name: 'Studio Wireless Headphones',
    department: 'Tech',
    summary: 'Over ear headphones with active noise cancelling and 30 hours of playback.',
    price: 19900,
    was: 24900,
    images: ['1505740420928-5e560c06d30e'],
    colors: ['black', 'white', 'yellow'],
    stock: 37,
    sales: 274,
    tags: ['headphones', 'audio', 'tech'],
    featured: true,
    bestseller: true,
  },
  {
    name: 'Navy Commuter Backpack',
    department: 'Bags',
    summary: 'A weatherproof backpack with a padded laptop sleeve and a hidden pocket.',
    price: 7900,
    was: 9900,
    images: ['1642375352634-ad952121fdb3'],
    colors: ['navy', 'black', 'grey'],
    stock: 54,
    sales: 197,
    tags: ['backpack', 'bag', 'travel'],
    featured: true,
  },
  {
    name: 'Oxblood Leather Backpack',
    department: 'Bags',
    summary: 'A full grain leather backpack that softens and darkens with every year of use.',
    price: 16400,
    was: 19900,
    images: ['1622560480654-d96214fdc887', '1622560257067-108402fcedc0'],
    colors: ['burgundy', 'tan'],
    stock: 23,
    sales: 104,
    tags: ['backpack', 'bag', 'leather'],
  },
  {
    name: 'Midnight Bowling Bag',
    department: 'Bags',
    summary: 'A structured bowling bag in pebbled leather with twin handles and a zip top.',
    price: 21900,
    was: 26900,
    images: ['1705909237050-7a7625b47fac'],
    colors: ['black', 'burgundy'],
    stock: 16,
    sales: 121,
    tags: ['bag', 'leather'],
    featured: true,
  },
  {
    name: 'Lemon Top Handle Bag',
    department: 'Bags',
    summary: 'A compact top handle bag in bright lemon leather with a push lock clasp.',
    price: 18900,
    images: ['1640901555383-7335ec5a6476'],
    colors: ['yellow', 'black', 'tan'],
    stock: 21,
    sales: 87,
    tags: ['bag', 'leather'],
  },
  {
    name: 'Teal Top Handle Bag',
    department: 'Bags',
    summary: 'A boxy handbag in deep teal leather with a detachable shoulder strap.',
    price: 17900,
    was: 21500,
    images: ['1594223274512-ad4803739b7c'],
    colors: ['green', 'black'],
    stock: 19,
    sales: 76,
    tags: ['bag', 'leather'],
  },
  {
    name: 'Saddle Leather Tote',
    department: 'Bags',
    summary: 'A roomy tote in vegetable tanned leather that only gets better with age.',
    price: 17400,
    was: 21000,
    images: ['1624687943971-e86af76d57de'],
    colors: ['tan', 'black'],
    stock: 24,
    sales: 99,
    tags: ['bag', 'tote', 'leather'],
  },
  {
    name: 'Chestnut Leather Handbag',
    department: 'Bags',
    summary: 'A classic handbag in polished chestnut leather with buckled side straps.',
    price: 15900,
    images: ['1691480150204-66dd1eb77391', '1691480250099-a63081ecfcb8'],
    colors: ['tan', 'burgundy'],
    stock: 26,
    sales: 93,
    tags: ['bag', 'leather'],
  },
  {
    name: 'Slate Leather Satchel',
    department: 'Bags',
    summary: 'A slim satchel in slate grey leather, sized for a tablet and the daily essentials.',
    price: 14900,
    was: 17900,
    images: ['1605733513597-a8f8341084e6'],
    colors: ['grey', 'black'],
    stock: 29,
    sales: 118,
    tags: ['bag', 'satchel', 'leather'],
  },
  {
    name: 'Heritage Messenger Satchel',
    department: 'Bags',
    summary: 'A rugged messenger satchel in oiled leather with twin buckle closures.',
    price: 18900,
    images: ['1473188588951-666fce8e7c68', '1603219527847-24c87f552a77'],
    colors: ['tan', 'burgundy'],
    stock: 18,
    sales: 84,
    tags: ['bag', 'satchel', 'leather'],
  },
  {
    name: 'Gold Link Bracelet',
    department: 'Jewellery',
    summary: 'A chunky link bracelet plated in 18 carat gold with a secure clasp.',
    price: 5400,
    images: ['1611591437281-460bfbe1220a'],
    colors: ['yellow'],
    stock: 59,
    sales: 141,
    tags: ['bracelet', 'jewellery', 'gold'],
  },
  {
    name: 'Gold Chain Necklace',
    department: 'Jewellery',
    summary: 'A layered chain necklace in warm gold plate that sits just below the collarbone.',
    price: 6800,
    images: ['1611107683227-e9060eccd846'],
    colors: ['yellow'],
    stock: 72,
    sales: 245,
    tags: ['necklace', 'jewellery', 'gold'],
    bestseller: true,
  },
  {
    name: 'Crystal Drop Earrings',
    department: 'Jewellery',
    summary: 'Hand set crystal drops that catch the light from every angle.',
    price: 4600,
    was: 5900,
    images: ['1535632066927-ab7c9ab60908'],
    colors: ['white', 'blue'],
    stock: 48,
    sales: 128,
    tags: ['earrings', 'jewellery'],
  },
  {
    name: 'Woven Straw Sun Hat',
    department: 'Headwear',
    summary: 'A hand woven straw hat with a wide brim that packs flat in a suitcase.',
    price: 3400,
    images: ['1718909603336-62fb533e6027', '1583238619747-27950824e04d'],
    colors: ['tan', 'white'],
    stock: 95,
    sales: 182,
    tags: ['hat', 'straw', 'summer'],
  },
  {
    name: 'Ribbon Straw Boater',
    department: 'Headwear',
    summary: 'A structured straw boater finished with a deep red grosgrain ribbon.',
    price: 3800,
    was: 4600,
    images: ['1698429518927-23645937bc2a'],
    colors: ['tan', 'red'],
    stock: 84,
    sales: 156,
    tags: ['hat', 'straw', 'summer'],
  },
  {
    name: 'Bifold Leather Wallet',
    department: 'Small Leather Goods',
    summary: 'A slim bifold with six card slots, cut from a single piece of leather.',
    price: 4900,
    images: ['1627123424574-724758594e93'],
    colors: ['tan', 'black'],
    stock: 77,
    sales: 215,
    tags: ['wallet', 'leather'],
    bestseller: true,
  },
  {
    name: 'Full Grain Leather Belt',
    department: 'Small Leather Goods',
    summary: 'A full grain leather belt with a solid brass buckle, made to last decades.',
    price: 4400,
    was: 5600,
    images: ['1624222247344-550fb60583dc'],
    colors: ['tan', 'black'],
    stock: 69,
    sales: 103,
    tags: ['belt', 'leather'],
  },
])

const shoes = build('shoes', [
  {
    name: 'Walnut Brogue Boot',
    department: 'Boots',
    summary: 'A lace up brogue boot in burnished walnut leather on a stitched welt sole.',
    price: 18900,
    was: 22900,
    images: ['1638609348722-aa2a3a67db26'],
    colors: ['tan', 'black'],
    stock: 52,
    sales: 391,
    tags: ['boots', 'brogue', 'leather'],
    featured: true,
    bestseller: true,
  },
  {
    name: 'Sand Suede Chelsea Boot',
    department: 'Boots',
    summary: 'A pull on Chelsea boot in soft sand suede with a buckled side strap.',
    price: 15900,
    images: ['1605733160314-4fc7dac4bb16'],
    colors: ['tan', 'grey'],
    stock: 35,
    sales: 129,
    tags: ['boots', 'suede'],
    featured: true,
  },
  {
    name: 'Black Zip Ankle Boot',
    department: 'Boots',
    summary: 'A sleek ankle boot in smooth black leather with a side zip and a low block heel.',
    price: 14900,
    was: 17900,
    images: ['1605732440685-d0654d81aa30'],
    colors: ['black', 'burgundy'],
    stock: 61,
    sales: 254,
    tags: ['boots', 'leather'],
    bestseller: true,
  },
  {
    name: 'Trail Leather Boot',
    department: 'Boots',
    summary: 'A waterproof leather boot with a lugged sole for trails and city winters.',
    price: 17900,
    was: 21900,
    images: ['1520639888713-7851133b1ed0'],
    colors: ['tan', 'black'],
    stock: 30,
    sales: 108,
    tags: ['boots', 'leather', 'outdoor'],
  },
  {
    name: 'Chestnut Bit Loafer',
    department: 'Smart Casual',
    summary: 'A hand stitched loafer in chestnut calf leather with a polished metal bit.',
    price: 13400,
    images: ['1616406432452-07bc5938759d'],
    colors: ['tan', 'black'],
    stock: 43,
    sales: 139,
    tags: ['loafers', 'leather'],
    featured: true,
  },
  {
    name: 'Tan Wingtip Brogue',
    department: 'Smart Casual',
    summary: 'A full wingtip brogue in tan leather, punched and stitched by hand.',
    price: 14400,
    was: 17400,
    images: ['1616663308968-58162d332720'],
    colors: ['tan', 'burgundy'],
    stock: 46,
    sales: 201,
    tags: ['brogue', 'leather'],
  },
  {
    name: 'Cognac Derby Shoe',
    department: 'Smart Casual',
    summary: 'An open laced derby in cognac leather, smart enough for the office.',
    price: 12900,
    images: ['1625357165350-bdbcb6d7d524'],
    colors: ['tan', 'black'],
    stock: 58,
    sales: 222,
    tags: ['derby', 'leather'],
    bestseller: true,
  },
  {
    name: 'Teal Suede Derby',
    department: 'Smart Casual',
    summary: 'A soft suede derby on a crepe sole, with a welcome flash of colour.',
    price: 10900,
    images: ['1560343090-f0409e92791a'],
    colors: ['green', 'tan', 'navy'],
    stock: 31,
    sales: 86,
    tags: ['derby', 'suede'],
  },
  {
    name: 'Stone Court Sneaker',
    department: 'Lifestyle',
    summary: 'A low top court sneaker in stone canvas with a contrast heel and a white cupsole.',
    price: 8900,
    was: 10900,
    images: ['1699092372473-a829f4421580'],
    colors: ['grey', 'white', 'red'],
    stock: 74,
    sales: 283,
    tags: ['sneakers', 'canvas'],
    featured: true,
    bestseller: true,
  },
  {
    name: 'Leather Slide Sandal',
    department: 'Sandals',
    summary: 'A two tone leather slide with a moulded footbed that shapes to your foot.',
    price: 6900,
    images: ['1585120824848-8a5cd41493d2'],
    colors: ['black', 'tan'],
    stock: 67,
    sales: 168,
    tags: ['sandals', 'leather'],
  },
  {
    name: 'Blush Strappy Sandal',
    department: 'Sandals',
    summary: 'A delicate strappy sandal in blush leather with an adjustable ankle tie.',
    price: 7900,
    was: 9600,
    images: ['1630407332126-70ebb700976b'],
    colors: ['pink', 'white'],
    stock: 41,
    sales: 147,
    tags: ['sandals', 'summer'],
  },
  {
    name: 'Cream Block Heel Sandal',
    department: 'Sandals',
    summary: 'An ankle strap sandal on a walkable block heel, in soft cream leather.',
    price: 9900,
    images: ['1595970487296-8818e128ac4b'],
    colors: ['white', 'tan'],
    stock: 50,
    sales: 176,
    tags: ['sandals', 'heels'],
  },
  {
    name: 'Maroon Platform Wedge',
    department: 'Sandals',
    summary: 'A buckled wedge in maroon leather on a lightweight platform sole.',
    price: 10400,
    was: 12900,
    images: ['1562273138-f46be4ebdf33'],
    colors: ['burgundy', 'black'],
    stock: 38,
    sales: 119,
    tags: ['wedges', 'sandals'],
  },
  {
    name: 'Cobalt Stiletto Heel',
    department: 'Occasion Wear',
    summary: 'A pointed stiletto in printed cobalt satin with a cushioned insole.',
    price: 13900,
    was: 16900,
    images: ['1543163521-1bf539c55dd2'],
    colors: ['blue', 'black', 'red'],
    stock: 25,
    sales: 93,
    tags: ['heels', 'occasion'],
  },
  {
    name: 'Scarlet Platform Heel',
    department: 'Occasion Wear',
    summary: 'A patent platform heel in scarlet with a peep toe and a slim ankle strap.',
    price: 14900,
    images: ['1670607231621-c00fd76d2387'],
    colors: ['red', 'black'],
    stock: 22,
    sales: 97,
    tags: ['heels', 'occasion'],
    featured: true,
  },
  {
    name: 'Nude Pointed Pump',
    department: 'Occasion Wear',
    summary: 'A pointed pump in nude leather that lengthens the leg and goes with everything.',
    price: 12400,
    was: 14900,
    images: ['1621996659490-3275b4d0d951'],
    colors: ['tan', 'black'],
    stock: 36,
    sales: 158,
    tags: ['heels', 'pumps'],
  },
  {
    name: 'Ivory Court Pump',
    department: 'Occasion Wear',
    summary: 'A textured court pump in ivory with a slender heel, made for long evenings.',
    price: 12900,
    images: ['1535043934128-cf0b28d52f95'],
    colors: ['white', 'tan'],
    stock: 28,
    sales: 111,
    tags: ['heels', 'pumps'],
  },
  {
    name: 'Black Pointed Pump',
    department: 'Occasion Wear',
    summary: 'The black pump every wardrobe needs, with a sharp toe and a steady heel.',
    price: 11900,
    was: 14400,
    images: ['1596703263926-eb0762ee17e4'],
    colors: ['black', 'red'],
    stock: 44,
    sales: 187,
    tags: ['heels', 'pumps'],
  },
])

export const products: SeedProduct[] = [...men, ...women, ...kids, ...accessories, ...shoes]

export interface SeedPost {
  slug: string
  title: string
  excerpt: string
  body: string[]
  image: string
  tags: string[]
  author: string
  badge: string
  commentCount: number
  publishedAt: string
}

export const posts: SeedPost[] = [
  {
    slug: 'build-a-capsule-wardrobe',
    title: 'How to build a capsule wardrobe that actually works',
    excerpt: 'Twelve pieces, thirty outfits. A practical guide to owning less and wearing more of it.',
    body: [
      'A capsule wardrobe is not about owning as little as possible. It is about making sure that everything you own earns its place, works with at least three other pieces, and suits the life you really live.',
      'Start by pulling out the clothes you wore most over the last month. Those pieces tell you more about your style than any trend report. Look at what they have in common: the colours, the fit, the fabric.',
      'From there, build outwards. Two pairs of trousers, one pair of jeans, three tees, two shirts, one knit, one jacket, one coat and one smart option is enough for most weeks. Keep the palette tight, then add one colour that makes you happy.',
      'The final step is the hardest: wait. Wear the capsule for a month before you buy anything new. You will quickly see what is missing, and you will buy far better because of it.',
    ],
    image: photo('1445205170230-053b83016050'),
    tags: ['Style', 'Trending', 'New'],
    author: 'Amelia Hart',
    badge: 'NEW',
    commentCount: 10,
    publishedAt: '2026-09-18T09:00:00.000Z',
  },
  {
    slug: 'how-to-care-for-leather',
    title: 'Leather care: make your jacket last twenty years',
    excerpt: 'Good leather gets better with age, but only if you look after it. Here is the routine we use.',
    body: [
      'Leather is skin, and like skin it dries out. The single best thing you can do for a jacket, a bag or a pair of boots is to condition it twice a year with a neutral balm.',
      'Wipe away dust with a barely damp cloth first. Work a small amount of conditioner in with circular motions, leave it for ten minutes, then buff with a clean cloth.',
      'If you get caught in the rain, let the leather dry slowly at room temperature. Never use a radiator or a hairdryer, heat is what causes cracking.',
      'Store leather on a wide hanger or stuffed with paper so it keeps its shape, and keep it out of plastic covers so it can breathe.',
    ],
    image: photo('1551028719-00167b16eac5'),
    tags: ['Care', 'Guides', 'Leather'],
    author: 'Marcus Doyle',
    badge: 'NEW',
    commentCount: 7,
    publishedAt: '2026-09-09T09:00:00.000Z',
  },
  {
    slug: 'sneaker-trends-this-season',
    title: 'Five sneaker trends worth your attention this season',
    excerpt: 'From retro runners to clean court shoes, these are the shapes we keep coming back to.',
    body: [
      'Chunky soles are finally slimming down. The shapes that look freshest right now are low, narrow and borrowed from seventies running shoes.',
      'White court sneakers remain the hardest working shoe you can own. Look for leather uppers and a stitched sole, they clean up well and last far longer.',
      'Colour is back, but in small doses: a bright heel tab, a contrast lining, a bold pair of laces.',
      'Whatever you choose, rotate your pairs. Giving a shoe a day to dry out between wears can double its life.',
    ],
    image: photo('1699092372473-a829f4421580'),
    tags: ['Shoes', 'Trending', 'New'],
    author: 'Priya Nair',
    badge: 'NEW',
    commentCount: 14,
    publishedAt: '2026-08-28T09:00:00.000Z',
  },
  {
    slug: 'inside-our-studio',
    title: 'Inside the studio: how a collection comes together',
    excerpt: 'We spent a week with the design team to see how an idea becomes something you can wear.',
    body: [
      'Every collection starts with a wall of fabric swatches and a lot of coffee. The team picks a palette first, then works out which shapes will carry it.',
      'Samples go through at least three rounds of fitting on people of different heights and builds. Small changes, a centimetre at the shoulder, a slightly deeper pocket, make the difference.',
      'Once a sample is approved it is wear tested for a month. Anything that pills, fades or loses its shape goes back to the drawing board.',
      'Only then does it go into production, in small batches so that nothing sits in a warehouse for long.',
    ],
    image: photo('1558769132-cb1aea458c5e'),
    tags: ['Studio', 'Behind the scenes'],
    author: 'Amelia Hart',
    badge: '',
    commentCount: 5,
    publishedAt: '2026-08-14T09:00:00.000Z',
  },
  {
    slug: 'dress-for-a-summer-wedding',
    title: 'What to wear to a summer wedding',
    excerpt: 'Dress codes decoded, from beach ceremonies to black tie in the heat.',
    body: [
      'The invitation is your first clue. If it says cocktail, think knee length dresses and unstructured suits. If it says formal, go longer and darker.',
      'Natural fabrics are your friend in the heat. Linen, cotton and lightweight wool breathe in a way that synthetics simply do not.',
      'Bring a layer for the evening, a fine knit or a light blazer, and choose shoes you can stand in for six hours.',
      'Finally, avoid white unless you are the one getting married. Some rules are worth keeping.',
    ],
    image: photo('1572804013309-59a88b7e92f1'),
    tags: ['Occasion', 'Guides'],
    author: 'Priya Nair',
    badge: '',
    commentCount: 9,
    publishedAt: '2026-07-30T09:00:00.000Z',
  },
  {
    slug: 'the-case-for-fewer-better-things',
    title: 'The case for fewer, better things',
    excerpt: 'Why we make in small batches, and what it means for the price on the tag.',
    body: [
      'Fast fashion is cheap at the till and expensive everywhere else. We would rather make a smaller number of pieces and make them well.',
      'Small batches mean we can use better fabrics, pay fair wages and avoid the mountain of unsold stock that big runs leave behind.',
      'It does mean that a popular size can sell out. When that happens we restock, but we do not rush it.',
      'The result is clothing that costs a little more and lasts a lot longer. Worked out per wear, it is the better deal.',
    ],
    image: photo('1489987707025-afc232f7ea0f'),
    tags: ['Sustainability', 'Studio'],
    author: 'Marcus Doyle',
    badge: '',
    commentCount: 12,
    publishedAt: '2026-07-16T09:00:00.000Z',
  },
]

export const coupons = [
  { code: 'WELCOME10', description: '10% off your first order', percentOff: 10, minSubtotal: 0 },
  { code: 'SUMMER20', description: '20% off orders over $80', percentOff: 20, minSubtotal: 8000 },
]

// Public demo account so visitors can try checkout and order history without
// registering. It is a normal customer and has no admin access.
export const demoUser = {
  name: 'Demo Shopper',
  // The .example domain is reserved and can never belong to anyone.
  email: 'demo@kainvara.example',
  password: 'demo-shopper-2026',
}

export const reviewers = [
  'Olivia M.',
  'Noah K.',
  'Emma R.',
  'Liam T.',
  'Ava S.',
  'Ethan B.',
  'Mia L.',
  'Lucas P.',
  'Sofia G.',
  'Jack W.',
]

export const reviewComments: Array<{ rating: number; title: string; comment: string }> = [
  { rating: 5, title: 'Exactly as described', comment: 'Great quality and it arrived two days early. Would happily order again.' },
  { rating: 5, title: 'My new favourite', comment: 'I have worn this almost every day since it arrived. It feels far more expensive than it was.' },
  { rating: 4, title: 'Really good', comment: 'Lovely quality. I took one star off because the colour is slightly darker than the photos.' },
  { rating: 5, title: 'Perfect fit', comment: 'True to size and very comfortable. The finishing is excellent.' },
  { rating: 4, title: 'Solid purchase', comment: 'Well made and good value. Delivery took a little longer than I expected.' },
  { rating: 5, title: 'Bought a second one', comment: 'So good that I came back for another colour. Washes well too.' },
  { rating: 3, title: 'Nice, runs a bit small', comment: 'The quality is good but I would size up next time.' },
  { rating: 5, title: 'Great gift', comment: 'Bought as a present and it went down really well. Nicely packaged.' },
  { rating: 4, title: 'Happy with it', comment: 'Does exactly what I wanted. Feels like it will last.' },
  { rating: 5, title: 'Better than expected', comment: 'The photos do not do it justice. Very pleased.' },
]
